---

- name: Configure rclone mounts
  register: systemd_service_result
  when: item.dest_path is defined
  template: src=rclone.service.j2 dest=/etc/systemd/system/{{ item.remote_src | regex_replace('\/','-') }}.service
  with_items: "{{ rclone_mounts }}"
  notify:
    - reload systemd
#    - restart rclone service
#    - restart rclone resource

- name: Configure rclone.conf
  import_tasks: rclone_post_install_config.yml

- name: Consul service definition
  when:
    - configure_consul | lower == 'true'
  notify: reload consul
  template: src=service.consul.json.j2 dest={{ rclone_consul_services_path }}/{{ item.remote_src | regex_replace('\/','-') }}.json
  with_items: "{{ rclone_mounts }}"

- name: Flushing handlers
  meta: flush_handlers

- name: Restart rclone mounts
  service: name={{ item.dest | regex_replace('^.+?(\\w+).service$','') }} state=restarted enabled=yes
  when: item.changed | lower == 'true'
  with_items: "{{ systemd_service_result.results }}"

- name: Restart rclone mounts
  service: name={{ item.item.remote_src | regex_replace('\/','-') }} state=restarted enabled=yes
  when: item.changed == true
  with_items: "{{ rclone_result.results }}"
 
- name: Start rclone mounts
  service: name={{ item.item.remote_src | regex_replace('\/','-') }} state=started enabled=yes
  with_items: "{{ rclone_result.results }}"

