---

- name: Configure rclone.conf (type)
  register: rclone_result
  with_items: "{{ rclone_mounts }}"
  ini_file:
    path: /root/.config/rclone/rclone.conf
    section: "{{ item.remote_src | regex_replace('^(\\w+)?\\:.+$', '\\1') }}"
    option: type
    value: swift
    mode: "{{ rclone_config_file_acl }}"

- name: Configure rclone.conf (user)
  register: rclone_result
  with_items: "{{ rclone_mounts }}"
  ini_file:
    path: /root/.config/rclone/rclone.conf
    section: "{{ item.remote_src | regex_replace('^(\\w+)?\\:.+$', '\\1') }}"
    option: user
    value: "{{ item.os_username }}"
    mode: "{{ rclone_config_file_acl }}"

- name: Configure rclone.conf (key)
  register: rclone_result
  with_items: "{{ rclone_mounts }}"
  ini_file:
    path: /root/.config/rclone/rclone.conf
    section: "{{ item.remote_src | regex_replace('^(\\w+)?\\:.+$', '\\1') }}"
    option: key
    value: "{{ item.os_password }}"
    mode: "{{ rclone_config_file_acl }}"

- name: Configure rclone.conf (auth)
  register: rclone_result
  with_items: "{{ rclone_mounts }}"
  ini_file:
    path: /root/.config/rclone/rclone.conf
    section: "{{ item.remote_src | regex_replace('^(\\w+)?\\:.+$', '\\1') }}"
    option: auth
    value: "{{ item.os_auth_url }}"
    mode: "{{ rclone_config_file_acl }}"

- name: Configure rclone.conf (tenant_id)
  register: rclone_result
  with_items: "{{ rclone_mounts }}"
  ini_file:
    path: /root/.config/rclone/rclone.conf
    section: "{{ item.remote_src | regex_replace('^(\\w+)?\\:.+$', '\\1') }}"
    option: tenant_id
    value: "{{ item.os_tenant_id }}"
    mode: "{{ rclone_config_file_acl }}"

- name: Configure rclone.conf (domain)
  register: rclone_result
  with_items: "{{ rclone_mounts }}"
  ini_file:
    path: /root/.config/rclone/rclone.conf
    section: "{{ item.remote_src | regex_replace('^(\\w+)?\\:.+$', '\\1') }}"
    option: domain
    value: "{{ item.os_domain | default('Default') }}"
    mode: "{{ rclone_config_file_acl }}"
