---

- name: Install | | Install rclone using packages
  when: rclone_use_docker | lower == 'false'
  block:
    - name: Install | | Install rclone packages
      package:
        name: "{{ rclone_distro_packages }}"
        state: "{{ rclone_package_state }}"
        update_cache: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
        cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
      register: install_packages
      until: install_packages is success
      retries: 5
      delay: 2
      tags:
        - install-apt
        - install-yum
        - install-zypper

    - name: Install | | Install rclone package from rclone.org
      when:
        - ansible_pkg_mgr == 'apt'
        - install_rclone | lower == 'true'
      apt:
        deb: "{{ package_url }}"
      register: install_packages
      until: install_packages is success
      retries: 5
      delay: 2
      tags:
        - install-apt
        - install-yum

    - name: Install | | Install rclone package from rclone.org
      when:
        - ansible_pkg_mgr == 'rpm'
        - install_rclone | lower == 'true'
      yum:
        name: "{{ package_url }}"
      register: install_packages
      until: install_packages is success
      retries: 5
      delay: 2
      tags:
        - install-apt
        - install-yum

- name: Install | | Pull docker image
  when: rclone_use_docker | lower == 'true'
  docker_image:
    name: "{{ rclone_docker_image }}"
    tag: "{{ rclone_docker_tag }}"
  register: pull_docker
  until: pull_docker is success
  retries: 5
  delay: 60
  tags:
    - pull-docker
