---

- name: Configure rclone mounts
  template: src=rclone.service.j2 dest=/etc/systemd/system/{{ item.remote_src | regex_replace('\/','-') }}.service
  with_items: "{{ rclone_mounts }}"
  notify:
    - reload systemd
#    - restart rclone service
#    - restart rclone resource

- name: Configure rclone.conf
  import_tasks: rclone_post_install_config.yml

- name: Consul service definition
  when:
    - configure_consul | lower == 'true'
  notify: reload consul
  template: src=service.consul.json.j2 dest={{ rclone_consul_services_path }}/{{ item.remote_src | regex_replace('\/','-') }}.json
  with_items: "{{ rclone_mounts }}"
