- name: Configure rclone.conf
  ini_file:
    path: /root/.config/rclone/rclone.conf
    section: "{{ item.name }}"
    option: type
    value: swift
    mode: 0600

- name: Configure rclone.conf
  ini_file:
    path: /root/.config/rclone/rclone.conf
    section: "{{ item.name }}"
    option: env_auth
    value: true
    mode: 0600

- name: Configure rclone.conf
  ini_file:
    path: /root/.config/rclone/rclone.conf
    section: "{{ item.name }}"
    option: endpoint_type
    value: public
    mode: 0600
