- name: Configure rclone.conf
  with_items:
    - option: type
      value: swift
    - option: user
      value: "{{ mount.os_username }}"
    - option: key
      value: "{{ mount.os_password }}"
    - option: auth
      value: "{{ mount.os_auth }}"
    - option: tenant_id
      value: "{{ mount.os_tenant_id }}"
    - option: domain
      value: "{{ mount.os_domain | default('Default') }}"
  ini_file:
    path: /root/.config/rclone/rclone.conf
    section: "{{ mount.remote_src | regex_replace('^(\\w+)?\\:.+$', '\\1') }}"
    option: type
    value: swift
    mode: 0600
