---

- name: Configure rclone mounts
  template: src=rclone.service.j2 dest=/etc/systemd/system/{{ item.remote_src | regex_replace('\/','-') }}.service
  with_items: "{{ rclone_mounts }}"
  notify:
    - reload systemd
#    - restart rclone service
#    - restart rclone resource

- name: Configure rclone sysconfig
  template: src=rclone.sysconfig.j2 dest={{ rclone_sysconfig}}/rclone-{{ item.remote_src | regex_replace('\/','-') }}
  with_items: "{{ rclone_mounts }}"

- name: Configure rclone.conf
  with_items: "{{ rclone_mounts }}"
  include_tasks: rclone_post_install_config.yml

#- name: Consul service definition
#  when:
#    - configure_consul | lower == 'true'
#  notify: reload consul
#  template: src=service.consul.json.j2 dest={{ rclone_consul_services_path }}/{{ item.service.name }}.json
#  with_items: "{{ rclone_consul }}"

#- name: (Re)start docker
#  when:
#    - rclone_cluster_aware | lower == 'false'
#    - rclone_use_docker | lower == 'true'
#  block:
#    - name: Start the container
#      docker_container:
#        state: started
#        name: rclone-server
#        image: "{{ rclone_docker_image }}"
#        published_ports: "{{ rclone_docker_published_ports }}"
#        volumes: "rclone_docker_volumes }}"
#        env: "{{ rclone_docker_env }}"
